services:
  - type: web
    name: whatsapp-ai-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
    healthCheckPath: /health
    autoDeploy: true 